on: [push]

jobs:
  hello_world_job:
    uses: floralatin/hub-actions/.github/workflows/hub-actions.yml@master
    with:
      action: 'all'
    secrets: 
      access_token: ${{ secrets.access_token }}