on: [push]

jobs:
  hub-actions:
    uses: jina-ai/hub-integration/.github/workflows/main.yml@build
    with:
      actions: 'sanity_check'
    secrets: 
      jin_dev_bot: ${{ secrets.JINA_DEV_BOT }}
      jina_auth_token: ${{ secrets.JINA_AUTH_TOKEN }}