on: [push]

jobs:
  hub-actions:
    uses: floralatin/hub-actions/.github/workflows/main.yml@master
    with:
      actions: 'alltest'
    secrets: 
      jin_dev_bot: ${{ secrets.JINA_DEV_BOT }}
      jina_auth_token: ${{ secrets.JINA_AUTH_TOKEN }}