on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: hello-javascript
        uses: floralatin/hub-action@v1.0
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Get hello-javascript the output
        run: echo "The time was ${{ steps.hello-javascript.outputs.result }}"